run:
  timeout: 5m

issues:
  exclude-rules:
    - path: ".*_test.go"
      linters:
        - funlen # tests are often long with many cases

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

  disable:
    - depguard # enforces dependency allow list; not using allow list
    - err113 # disallows returning one-off errors; annoying
    - gochecknoglobals # disallows global variables; used for parsec atoms
    - gofumpt # different code formatter; bad
    - nlreturn # requires blank line before return; annoying
    - tagliatelle # enforces struct tag format; annoying, often wrong
    - varnamelen # limits variable name length; too many false positives
    - wsl # whitespace/cuddle rules; tedious
